name: pubmind
description: An intelligent AI agent that recommends and auto-installs pub.dev packages with smart compatibility checking and conflict resolution.
version: 0.1.0
homepage: https://github.com/VenbrinoDevelopers/pubmind
repository: https://github.com/VenbrinoDevelopers/pubmind
issue_tracker: https://github.com/VenbrinoDevelopers/pubmind/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  cli_util: ^0.4.0
  mason_logger: ^0.3.3
  cli_spin: ^1.0.1
  interact: ^2.2.0
  langchain: ^0.8.0+1
  langchain_openai: ^0.8.0+1
  langchain_community: ^0.4.0+1
  http: ^1.1.0
  pub_api_client: ^2.6.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1
  pub_semver: ^2.1.4
  path: ^1.9.1
  acanthis: ^1.4.5
  collection: ^1.19.1
 
  
 
dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
  mocktail: ^1.0.0

executables:
  pubmind: